version: "3.7"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=node_todos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
